{
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie',
        width: 800,
        height: 400
    },
    title: {
        text: 'Sample PIE generated by RaaS'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.y:.1f}'
            },
            showInLegend: true
        }
    },
    series: [{
        name: '$TITLE$',
        colorByPoint: true,
        data: [$DATA$]
    }]
}